### ISSUE TITLE
Demo instance does not work

### ISSUE THREAD

**Issue by wmertens** [googlearchive/realtime-tasks#9]
Console log says `gapi` is not defined.

**Comment by perqa** [comment]
It used to work, but not anymore. Just adding the demo URL: http://googledrive.github.io/realtime-tasks.

I get the following error message:
 `Uncaught TypeError: Cannot read property 'prototype' of undefined`        `cb=gapi.loaded_0:516`

**Comment by erickoledadevrel** [comment]
I believe this broke as a result of some classes being hidden: http://stackoverflow.com/questions/26664460/was-the-drive-realtime-api-changed-today

**Comment by perqa** [comment]
The error is caused by the "Monkey Patch" in app.js.  
**gapi.drive.realtime.CollaborativeString** is undefined. Not sure how to address this issue.

```
// Monkey patch collaborative string for ng-model compatibility
  Object.defineProperty(gapi.drive.realtime.CollaborativeString.prototype, 'text', {
    set: gapi.drive.realtime.CollaborativeString.prototype.setText,
    get: gapi.drive.realtime.CollaborativeString.prototype.getText
  });
```

**Comment by erickoledadevrel** [comment]
I have an outstanding [pull request](https://github.com/googledrive/realtime-tasks/pull/10) that should fix it.

**Comment by perqa** [comment]
@erickoledadevrel < Thanks! I got it _mostly_ working from your fork. I still can't get sharing to work, and this is the error message I see in the console:

```
drive.google.com/share?id=0Bz5QQP8x8CdPdlQzRHM1cnJCRFk&foreignService=explo…ssage&appId=980065486707&embedOrigin=http%3A%2F%2Fdev.quested.net%3A9010:1 
Refused to display 'https://accounts.google.com/AccountChooser?service=wise&continue=https%3A%2…D980065486707%26embedOrigin%3Dhttp%3A%2F%2Fdev.quested.net%3A9010%23&hl=sv' 
in a frame because it set 'X-Frame-Options' to 'DENY'.
```

Is it due to some setting on my side, or is it a bug?

**Comment by perqa** [comment]
This bug might have been closed prematurely: the demo instance is still broken.

**Comment by erickoledadevrel** [comment]
Sorry, I had to publish the compiled pages to the gh-pages branch. Now fixed.

**Comment by erickoledadevrel** [comment]
Regarding the X-Frame-Options error, that is due to not configuring the Drive SDK correctly. See the updated README.
